openapi: 3.0.0
info:
  description: This API recieves burger order events from customers and assigns deliveries to drivers
  version: "1.0.0"
  title: Burger ordering API
  contact:
    email: klow23@my.bcit.ca
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: orders
    description: Operations available to customer orders
  - name: deliveries
    description: Operations available to delivery scheduling
paths:
  /getorders:
    get:
      tags:
        - orders
      summary: gets new orders
      operationId: app.get_orders
      description: Gets orders added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits number of items on a page greater/equal to the time
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits number of items on a page less than the time
          schema:
            type: string
            format: date-time
            example: 2016-08-29T10:20:33.001Z
      responses:
        "200":
          description: Successfully returned a list of order events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderItem"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /getdeliveries:
    get:
      tags:
        - deliveries
      summary: gets new deliveries
      operationId: app.get_deliveries
      description: Gets deliveries added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits number of items on a page greater/equal to the time
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits number of items on a page less than the time
          schema:
            type: string
            format: date-time
            example: 2016-08-29T10:12:33.001Z
      responses:
        "200":
          description: Successfully returned a list of delivery events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeliveryItem"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /health:
    get:
      summary: get service health
      operationId: app.get_health
      description: Get service health every 5 seconds
      responses:
        "200":
          description: Service is running

components:
  schemas:
    OrderItem:
      type: object
      required:
        - customer_name
        - customer_phone
        - is_delivery
        - order_address
        - burger_name
        - order_quantity
        - order_total
        - order_tip
        - order_timestamp
        - trace_id
      properties:
        customer_name:
          type: string
          example: "John Doe"
        customer_phone:
          type: string
          example: "778-668-2818"
        is_delivery:
          type: boolean
          example: "true"
        order_address:
          type: string
          example: "5855 Sherbrooke Street"
        burger_name:
          type: string
          example: "Juicy Original"
        order_quantity:
          type: integer
          example: 3
        order_total:
          type: number
          example: 13.50
        order_tip:
          type: number
          example: 5.00
        order_timestamp:
          example: "2023-09-07T012:15:33.001Z"
        trace_id:
          type: string
    DeliveryItem:
      type: object
      required:
        - order_id
        - driver_id
        - assignment_timestamp
        - fulfilment_timestamp
        - delivery_distance
        - delivery_tip
        - trace_id
      properties:
        order_id:
          type: integer
          example: 2
        driver_id:
          type: integer
          example: 20
        assignment_timestamp:
          type: string
          format: date-time
          example: "2023-09-07T012:16:33.001Z"
        fulfilment_timestamp:
          type: string
          format: date-time
          example: "2023-09-07T012:34:33.001Z"
        delivery_distance:
          type: number
          example: 0.2
        delivery_tip:
          type: number
          example: 2.50
        trace_id:
          type: string
